Import relevant libraries

In [ ]:
import numpy


In [32]:
s = 5

In [33]:
s

5

In [34]:
v  = numpy.array([5, -2, 4])

v

array([ 5, -2,  4])

In [35]:
m = numpy.array([[5, 12, 6], [-3, 0, 14]])

m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [36]:
type(s)


int

In [37]:
type(v)

numpy.ndarray

In [38]:
type(m)

numpy.ndarray

In [39]:
s_array = numpy.array([5]) 

type(s_array)

numpy.ndarray

In [40]:
m.shape

(2, 3)

In [41]:
v.shape

(3,)

In [42]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [43]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

Tensors

In [44]:
m1 = numpy.array([[5,12,6], [-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [45]:
m2 = numpy.array([[9, 8, 7], [1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [46]:
t = numpy.array([m1, m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [47]:
t.shape

(2, 2, 3)